const orders=[
{id:'UT-1048',store:'Yonge & Sheppard',initial:'YS',delivery:'Fri, Sep 18',original:'12 full · 2 half',choc:'4 full',pack:'120 boxes',status:'Approved'},
{id:'UT-1049',store:'Union Station',initial:'US',delivery:'Fri, Sep 18',original:'10 full',choc:'3 full · 1 half',pack:'95 boxes',status:'In production'},
{id:'UT-1050',store:'Pacific Mall',initial:'PM',delivery:'Sat, Sep 19',original:'14 full · 1 half',choc:'5 full',pack:'140 boxes',status:'Submitted'},
{id:'UT-1051',store:'Square One',initial:'SQ',delivery:'Sat, Sep 19',original:'9 full · 2 half',choc:'4 full',pack:'100 boxes',status:'Approved'},
{id:'UT-1052',store:'Richmond BC',initial:'RB',delivery:'Mon, Sep 21',original:'18 full',choc:'6 full · 2 half',pack:'180 boxes',status:'Draft'},
{id:'UT-1053',store:'Markham',initial:'MK',delivery:'Mon, Sep 21',original:'8 full · 1 half',choc:'2 full',pack:'80 boxes',status:'Submitted'}];
const products=[
{id:'original-full',name:'Original Cheesecake',variant:'Full batch',detail:'5 cakes per batch',unit:'batch',yield:5,category:'bakery',icon:'◉',tone:'original'},
{id:'original-half',name:'Original Cheesecake',variant:'Half batch',detail:'2.5 cakes per batch',unit:'half batch',yield:2.5,category:'bakery',icon:'◉',tone:'original'},
{id:'chocolate-full',name:'Chocolate Cheesecake',variant:'Full batch',detail:'5 cakes per batch',unit:'batch',yield:5,category:'bakery',icon:'◉',tone:'chocolate'},
{id:'tarts-full',name:'Cheese Tarts',variant:'Full batch',detail:'30 tarts per batch',unit:'batch',yield:30,category:'bakery',icon:'✿',tone:'tart'},
{id:'cake-boxes',name:'Cheesecake Boxes',variant:'Case of 50',detail:'Food-safe printed boxes',unit:'case',yield:50,category:'packaging',icon:'□',tone:'box'},
{id:'tart-trays',name:'Tart Trays',variant:'Case of 100',detail:'Six-cavity retail trays',unit:'case',yield:100,category:'packaging',icon:'▦',tone:'tray'}];
const tickets=[
{id:'ISS-0247',title:'Mixer making grinding noise',store:'Yonge & Sheppard',category:'Equipment',priority:'High',status:'In progress',assigned:'LT',assignee:'Leti',updated:'12 min ago',desc:'The main 20L mixer started making a grinding noise during the morning batch.'},
{id:'ISS-0246',title:'Walk-in cooler temperature fluctuating',store:'Union Station',category:'Facilities',priority:'High',status:'Open',assigned:'DM',assignee:'Daniel',updated:'42 min ago',desc:'Temperature moved between 3°C and 8°C overnight. Products relocated as a precaution.'},
{id:'ISS-0244',title:'Short shipment of cake boxes',store:'Pacific Mall',category:'Supplies',priority:'Medium',status:'Waiting',assigned:'LT',assignee:'Leti',updated:'Yesterday',desc:'Received 6 cases instead of 10 on purchase order PO-8812.'},
{id:'ISS-0241',title:'POS receipt printer offline',store:'Square One',category:'Technology',priority:'Low',status:'In progress',assigned:'AK',assignee:'Akira',updated:'Yesterday',desc:'Front counter receipt printer is offline after yesterday’s update.'}];
const cart={'original-full':12,'original-half':2,'chocolate-full':4,'cake-boxes':3};
const statusClass=s=>s.toLowerCase().replaceAll(' ','-');
function renderOrders(){document.querySelector('#ordersTable').innerHTML=orders.map(o=>`<tr><td><strong>${o.id}</strong></td><td><div class="store-cell"><span class="store-dot">${o.initial}</span><strong>${o.store}</strong></div></td><td>${o.delivery}</td><td><span class="status ${statusClass(o.status)}">● ${o.status}</span></td></tr>`).join('');document.querySelector('#dashOrders').innerHTML=orders.slice(0,4).map(o=>`<tr><td><div class="store-cell"><span class="store-dot">${o.initial}</span><strong>${o.store}</strong></div></td><td>${o.delivery}</td><td>${o.original.split(' · ')[0]}</td><td><span class="status ${statusClass(o.status)}">${o.status}</span></td></tr>`).join('')}
function renderCatalog(category='all'){document.querySelector('#productCatalog').innerHTML=products.filter(p=>category==='all'||p.category===category).map(p=>`<article class="product-row ${cart[p.id]?'selected':''}" data-product="${p.id}"><div class="product-icon ${p.tone}">${p.icon}</div><div class="product-info"><h3>${p.name}</h3><span>${p.variant}</span><small>${p.detail}</small></div><div class="qty-control"><button aria-label="Remove one" data-step="-1">−</button><strong>${cart[p.id]||0}</strong><button aria-label="Add one" data-step="1">＋</button></div></article>`).join('')}
function changeQty(id,delta){cart[id]=Math.max(0,(cart[id]||0)+delta);if(!cart[id])delete cart[id];renderCatalog(document.querySelector('#catalogTabs .active').dataset.category);renderCart()}
function renderCart(){const lines=products.filter(p=>cart[p.id]);const empty=document.querySelector('#cartEmpty');empty.style.display=lines.length?'none':'grid';document.querySelector('#cartLines').innerHTML=lines.map(p=>`<div class="cart-line"><div><strong>${p.name}</strong><span>${p.variant} · ${cart[p.id]} ${cart[p.id]===1?p.unit:p.unit+'es'.replace('batcheses','batches')}</span></div><div><b>${cart[p.id]}</b><button data-remove="${p.id}" aria-label="Remove">×</button></div></div>`).join('');let bakery=lines.filter(p=>p.category==='bakery').reduce((n,p)=>n+cart[p.id],0), units=lines.reduce((n,p)=>n+cart[p.id]*p.yield,0);document.querySelector('#lineCount').textContent=lines.length;document.querySelector('#batchTotal').textContent=bakery;document.querySelector('#unitTotal').textContent=Number.isInteger(units)?units:units.toFixed(1);document.querySelector('#summaryTotals').style.display=lines.length?'grid':'none';document.querySelector('#reviewOrder').disabled=!lines.length}
function updateContext(){const store=document.querySelector('#orderStore').value,date=new Date(document.querySelector('#deliveryDate').value+'T12:00:00');document.querySelector('#summaryStore').textContent=store;document.querySelector('#summaryDelivery').textContent='Delivery '+date.toLocaleDateString('en-CA',{weekday:'short',month:'short',day:'numeric'})}
function renderTickets(){document.querySelector('#issueList').innerHTML=tickets.slice(0,3).map(t=>`<div class="issue"><i class="priority-dot ${t.priority==='Medium'?'med':''}"></i><div><strong>${t.title}</strong><span>${t.store} · ${t.updated}</span></div><span class="assignee">${t.assigned}</span></div>`).join('');document.querySelector('#ticketCards').innerHTML=tickets.map(t=>`<article class="ticket-card" data-ticket="${t.id}"><div><div class="ticket-top"><span class="ticket-id">${t.id}</span><span class="priority ${t.priority.toLowerCase()}">${t.priority.toUpperCase()}</span></div><h3>${t.title}</h3><p>${t.desc}</p><div class="ticket-meta"><span>⌖ ${t.store}</span><span>▣ ${t.category}</span><span>◷ Updated ${t.updated}</span><span>▧ ${t.id==='ISS-0247'?'2 photos':'No photos'}</span></div></div><div class="ticket-right"><span class="status ${statusClass(t.status)}">● ${t.status}</span><div class="people"><span class="assignee">${t.assigned}</span>${t.assignee}</div></div></article>`).join('')}
const names={dashboard:'Dashboard',orders:'Store Orders',factory:'Factory Plan',tickets:'Issue Tickets',recipes:'Recipes & Batches'};
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelector('#crumb').textContent=names[page];document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
document.querySelector('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b)go(b.dataset.page)};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelector('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelectorAll('[data-action="new-order"]').forEach(b=>b.onclick=()=>go('orders'));
document.querySelector('#catalogTabs').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;document.querySelectorAll('#catalogTabs button').forEach(x=>x.classList.toggle('active',x===b));renderCatalog(b.dataset.category)};document.querySelector('#productCatalog').onclick=e=>{const b=e.target.closest('[data-step]');if(b)changeQty(b.closest('[data-product]').dataset.product,Number(b.dataset.step))};document.querySelector('#cartLines').onclick=e=>{const b=e.target.closest('[data-remove]');if(b)changeQty(b.dataset.remove,-cart[b.dataset.remove])};document.querySelector('#clearCart').onclick=()=>{Object.keys(cart).forEach(k=>delete cart[k]);renderCatalog(document.querySelector('#catalogTabs .active').dataset.category);renderCart()};document.querySelector('#orderStore').onchange=updateContext;document.querySelector('#deliveryDate').onchange=updateContext;document.querySelector('#toggleHistory').onclick=()=>{const h=document.querySelector('#orderHistory'),open=h.classList.toggle('collapsed');document.querySelector('#toggleHistory').textContent=open?'Show orders ↓':'Hide orders ↑'};
const modal=document.querySelector('#modal'),body=document.querySelector('#modalBody');function showTicket(){body.innerHTML=`<h2>Report an issue</h2><p>Create a trackable issue for a store or factory team.</p><div class="form-grid"><label class="span2">Issue title<input value="Broken mixer"></label><label>Location<select><option>Yonge & Sheppard</option><option>Union Station</option><option>Factory - Toronto</option></select></label><label>Priority<select><option>High</option><option>Medium</option><option>Low</option></select></label><label>Assign to<select><option>Leti</option><option>Daniel</option><option>Akira</option></select></label><label>Status<select><option>Open</option><option>Pending</option><option>In progress</option></select></label><label class="span2">Details<textarea>20L mixer stopped during the morning production run.</textarea></label></div><div class="modal-actions"><button class="secondary cancel">Cancel</button><button class="primary save">Create ticket</button></div>`;modal.classList.add('open');body.querySelector('.cancel').onclick=close;body.querySelector('.save').onclick=demoToast}function close(){modal.classList.remove('open')}function demoToast(){close();let t=document.querySelector('#toast');t.textContent='Demo action complete. This preview does not save data.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
document.querySelector('[data-action="new-ticket"]').onclick=showTicket;document.querySelector('#reviewOrder').onclick=()=>{const lines=products.filter(p=>cart[p.id]);body.innerHTML=`<h2>Review store order</h2><p>${document.querySelector('#summaryStore').textContent} · ${document.querySelector('#summaryDelivery').textContent}</p><div class="review-lines">${lines.map(p=>`<div><span>${p.name}<small>${p.variant}</small></span><strong>× ${cart[p.id]}</strong></div>`).join('')}</div><div class="note"><strong>Ready for factory review</strong><p>Submitting will send this order to the production team.</p></div><div class="modal-actions"><button class="secondary cancel">Back to order</button><button class="primary save">Submit order</button></div>`;modal.classList.add('open');body.querySelector('.cancel').onclick=close;body.querySelector('.save').onclick=demoToast};document.querySelector('#closeModal').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.querySelector('.ticket-cards').onclick=e=>{let c=e.target.closest('.ticket-card');if(c){let t=tickets.find(x=>x.id===c.dataset.ticket);body.innerHTML=`<h2>${t.title}</h2><p>${t.id} · ${t.store}</p><div class="note"><strong>Current status: ${t.status}</strong><p>Assigned to ${t.assignee} · Updated ${t.updated}</p></div>`;modal.classList.add('open')}};
renderOrders();renderTickets();renderCatalog();renderCart();updateContext();
